config/routes.rb
AirForce::Application.routes.draw do

  resources :servicios

  resources :anotacions

  resources :alumnos_x_cursos

  resources :asignatura_x_cursos

  resources :cursos

  resources :asignaturas

  resources :profesors

  resources :alumnos

  match '/about', :to => 'static_pages#about'
    
  root :to => 'static_pages#home'

  

end

app/models/asignatura.rb
class Asignatura < ActiveRecord::Base
  has_many :asignatura_x_cursos
end

app/controllers/asignaturas_controller.rb
class AsignaturasController < ApplicationController
  # GET /asignaturas
  # GET /asignaturas.json
  def index
    @asignaturas = Asignatura.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @asignaturas }
    end
  end

  # GET /asignaturas/1
  # GET /asignaturas/1.json
  def show
    @asignatura = Asignatura.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @asignatura }
    end
  end

  # GET /asignaturas/new
  # GET /asignaturas/new.json
  def new
    @asignatura = Asignatura.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @asignatura }
    end
  end

  # GET /asignaturas/1/edit
  def edit
    @asignatura = Asignatura.find(params[:id])
  end

  # POST /asignaturas
  # POST /asignaturas.json
  def create
    @asignatura = Asignatura.new(params[:asignatura])

    respond_to do |format|
      if @asignatura.save
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully created.' }
        format.json { render json: @asignatura, status: :created, location: @asignatura }
      else
        format.html { render action: "new" }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /asignaturas/1
  # PUT /asignaturas/1.json
  def update
    @asignatura = Asignatura.find(params[:id])

    respond_to do |format|
      if @asignatura.update_attributes(params[:asignatura])
        format.html { redirect_to @asignatura, notice: 'Asignatura was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @asignatura.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /asignaturas/1
  # DELETE /asignaturas/1.json
  def destroy
    @asignatura = Asignatura.find(params[:id])
    @asignatura.destroy

    respond_to do |format|
      format.html { redirect_to asignaturas_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/asignaturas_helper.rb
module AsignaturasHelper
end

app/views/asignaturas/_form.html.erb
<%= form_for(@asignatura) do |f| %>
  <% if @asignatura.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@asignatura.errors.count, "error") %> prohibited this asignatura from being saved:</h2>

      <ul>
      <% @asignatura.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :codigo %><br />
    <%= f.text_field :codigo %>
  </div>
  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :tipo %><br />
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :numero_notas_parciales %><br />
    <%= f.number_field :numero_notas_parciales %>
  </div>
  <div class="field">
    <%= f.label :examen %><br />
    <%= f.check_box :examen %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/asignaturas/edit.html.erb
<h1>Editing asignatura</h1>

<%= render 'form' %>

<%= link_to 'Show', @asignatura %> |
<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/index.html.erb
<h1>Listing asignaturas</h1>

<table>
  <tr>
    <th>Codigo</th>
    <th>Nombre</th>
    <th>Tipo</th>
    <th>Numero notas parciales</th>
    <th>Examen</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @asignaturas.each do |asignatura| %>
  <tr>
    <td><%= asignatura.codigo %></td>
    <td><%= asignatura.nombre %></td>
    <td><%= asignatura.tipo %></td>
    <td><%= asignatura.numero_notas_parciales %></td>
    <td><%= asignatura.examen %></td>
    <td><%= link_to 'Show', asignatura %></td>
    <td><%= link_to 'Edit', edit_asignatura_path(asignatura) %></td>
    <td><%= link_to 'Destroy', asignatura, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Asignatura', new_asignatura_path %>

app/views/asignaturas/new.html.erb
<h1>New asignatura</h1>

<%= render 'form' %>

<%= link_to 'Back', asignaturas_path %>

app/views/asignaturas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Codigo:</b>
  <%= @asignatura.codigo %>
</p>

<p>
  <b>Nombre:</b>
  <%= @asignatura.nombre %>
</p>

<p>
  <b>Tipo:</b>
  <%= @asignatura.tipo %>
</p>

<p>
  <b>Numero notas parciales:</b>
  <%= @asignatura.numero_notas_parciales %>
</p>

<p>
  <b>Examen:</b>
  <%= @asignatura.examen %>
</p>


<%= link_to 'Edit', edit_asignatura_path(@asignatura) %> |
<%= link_to 'Back', asignaturas_path %>