config/routes.rb
AirForce::Application.routes.draw do

  resources :servicios

  resources :anotacions

  resources :alumnos_x_cursos

  resources :asignatura_x_cursos

  resources :cursos

  resources :asignaturas

  resources :profesors

  resources :alumnos

  match '/about', :to => 'static_pages#about'
    
  root :to => 'static_pages#home'

  

end

app/models/anotacion.rb
class Anotacion < ActiveRecord::Base
  belongs_to :alumno
end

app/controllers/anotacions_controller.rb
class AnotacionsController < ApplicationController
  # GET /anotacions
  # GET /anotacions.json
  def index
    @anotacions = Anotacion.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @anotacions }
    end
  end

  # GET /anotacions/1
  # GET /anotacions/1.json
  def show
    @anotacion = Anotacion.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @anotacion }
    end
  end

  # GET /anotacions/new
  # GET /anotacions/new.json
  def new
    @anotacion = Anotacion.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @anotacion }
    end
  end

  # GET /anotacions/1/edit
  def edit
    @anotacion = Anotacion.find(params[:id])
  end

  # POST /anotacions
  # POST /anotacions.json
  def create
    @anotacion = Anotacion.new(params[:anotacion])

    respond_to do |format|
      if @anotacion.save
        format.html { redirect_to @anotacion, notice: 'Anotacion was successfully created.' }
        format.json { render json: @anotacion, status: :created, location: @anotacion }
      else
        format.html { render action: "new" }
        format.json { render json: @anotacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /anotacions/1
  # PUT /anotacions/1.json
  def update
    @anotacion = Anotacion.find(params[:id])

    respond_to do |format|
      if @anotacion.update_attributes(params[:anotacion])
        format.html { redirect_to @anotacion, notice: 'Anotacion was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @anotacion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /anotacions/1
  # DELETE /anotacions/1.json
  def destroy
    @anotacion = Anotacion.find(params[:id])
    @anotacion.destroy

    respond_to do |format|
      format.html { redirect_to anotacions_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/anotacions_helper.rb
module AnotacionsHelper
end

app/views/anotacions/_form.html.erb
<%= form_for(@anotacion) do |f| %>
  <% if @anotacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anotacion.errors.count, "error") %> prohibited this anotacion from being saved:</h2>

      <ul>
      <% @anotacion.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fecha %><br />
    <%= f.date_select :fecha %>
  </div>
  <div class="field">
    <%= f.label :anotacion %><br />
    <%= f.text_area :anotacion %>
  </div>
  <div class="field">
    <%= f.label :meritos %><br />
    <%= f.number_field :meritos %>
  </div>
  <div class="field">
    <%= f.label :demeritos %><br />
    <%= f.number_field :demeritos %>
  </div>
  <div class="field">
    <%= f.label :calificador %><br />
    <%= f.text_field :calificador %>
  </div>
  <div class="field">
    <%= f.label :alumno_id %><br />
    <%= f.collection_select :alumno_id, Alumno.all, :id, :rut, :prompt => 'Selecciona un alumno' %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/anotacions/edit.html.erb
<h1>Editing anotacion</h1>

<%= render 'form' %>

<%= link_to 'Show', @anotacion %> |
<%= link_to 'Back', anotacions_path %>

app/views/anotacions/index.html.erb
<h1>Listing anotacions</h1>

<table>
  <tr>
    <th>Fecha</th>
    <th>Anotacion</th>
    <th>Meritos</th>
    <th>Demeritos</th>
    <th>Calificador</th>
    <th>Alumno</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @anotacions.each do |anotacion| %>
  <tr>
    <td><%= anotacion.fecha %></td>
    <td><%= anotacion.anotacion %></td>
    <td><%= anotacion.meritos %></td>
    <td><%= anotacion.demeritos %></td>
    <td><%= anotacion.calificador %></td>
    <td><%= anotacion.alumno.apellido_paterno + " " + anotacion.alumno.apellido_materno + " " + anotacion.alumno.nombres %></td>
    <td><%= link_to 'Show', anotacion %></td>
    <td><%= link_to 'Edit', edit_anotacion_path(anotacion) %></td>
    <td><%= link_to 'Destroy', anotacion, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Anotacion', new_anotacion_path %>

app/views/anotacions/new.html.erb
<h1>New anotacion</h1>

<%= render 'form' %>

<%= link_to 'Back', anotacions_path %>

app/views/anotacions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Fecha:</b>
  <%= @anotacion.fecha %>
</p>

<p>
  <b>Anotacion:</b>
  <%= @anotacion.anotacion %>
</p>

<p>
  <b>Meritos:</b>
  <%= @anotacion.meritos %>
</p>

<p>
  <b>Demeritos:</b>
  <%= @anotacion.demeritos %>
</p>

<p>
  <b>Calificador:</b>
  <%= @anotacion.calificador %>
</p>

<p>
  <b>Alumno:</b>
  <%= @anotacion.alumno.apellido_paterno + " " + @anotacion.alumno.apellido_materno + " " +@anotacion.alumno.nombres %>
</p>


<%= link_to 'Edit', edit_anotacion_path(@anotacion) %> |
<%= link_to 'Back', anotacions_path %>