config/routes.rb
AirForce::Application.routes.draw do

  resources :servicios

  resources :anotacions

  resources :alumnos_x_cursos

  resources :asignatura_x_cursos

  resources :cursos

  resources :asignaturas

  resources :profesors

  resources :alumnos

  match '/about', :to => 'static_pages#about'
    
  root :to => 'static_pages#home'

  

end

app/models/profesor.rb
class Profesor < ActiveRecord::Base
end

app/controllers/profesors_controller.rb
class ProfesorsController < ApplicationController
  # GET /profesors
  # GET /profesors.json
  def index
    @profesors = Profesor.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @profesors }
    end
  end

  # GET /profesors/1
  # GET /profesors/1.json
  def show
    @profesor = Profesor.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @profesor }
    end
  end

  # GET /profesors/new
  # GET /profesors/new.json
  def new
    @profesor = Profesor.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @profesor }
    end
  end

  # GET /profesors/1/edit
  def edit
    @profesor = Profesor.find(params[:id])
  end

  # POST /profesors
  # POST /profesors.json
  def create
    @profesor = Profesor.new(params[:profesor])

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render json: @profesor, status: :created, location: @profesor }
      else
        format.html { render action: "new" }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /profesors/1
  # PUT /profesors/1.json
  def update
    @profesor = Profesor.find(params[:id])

    respond_to do |format|
      if @profesor.update_attributes(params[:profesor])
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesors/1
  # DELETE /profesors/1.json
  def destroy
    @profesor = Profesor.find(params[:id])
    @profesor.destroy

    respond_to do |format|
      format.html { redirect_to profesors_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/profesors_helper.rb
module ProfesorsHelper
end

app/views/profesors/_form.html.erb
<%= form_for(@profesor) do |f| %>
  <% if @profesor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@profesor.errors.count, "error") %> prohibited this profesor from being saved:</h2>

      <ul>
      <% @profesor.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :rut %><br />
    <%= f.text_field :rut %>
  </div>
  <div class="field">
    <%= f.label :nombres %><br />
    <%= f.text_field :nombres %>
  </div>
  <div class="field">
    <%= f.label :apellido_paterno %><br />
    <%= f.text_field :apellido_paterno %>
  </div>
  <div class="field">
    <%= f.label :apellido_materno %><br />
    <%= f.text_field :apellido_materno %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/profesors/edit.html.erb
<h1>Editing profesor</h1>

<%= render 'form' %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesors_path %>

app/views/profesors/index.html.erb
<h1>Listing profesors</h1>

<table>
  <tr>
    <th>Rut</th>
    <th>Nombres</th>
    <th>Apellido paterno</th>
    <th>Apellido materno</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @profesors.each do |profesor| %>
  <tr>
    <td><%= profesor.rut %></td>
    <td><%= profesor.nombres %></td>
    <td><%= profesor.apellido_paterno %></td>
    <td><%= profesor.apellido_materno %></td>
    <td><%= profesor.email %></td>
    <td><%= link_to 'Show', profesor %></td>
    <td><%= link_to 'Edit', edit_profesor_path(profesor) %></td>
    <td><%= link_to 'Destroy', profesor, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Profesor', new_profesor_path %>

app/views/profesors/new.html.erb
<h1>New profesor</h1>

<%= render 'form' %>

<%= link_to 'Back', profesors_path %>

app/views/profesors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Rut:</b>
  <%= @profesor.rut %>
</p>

<p>
  <b>Nombres:</b>
  <%= @profesor.nombres %>
</p>

<p>
  <b>Apellido paterno:</b>
  <%= @profesor.apellido_paterno %>
</p>

<p>
  <b>Apellido materno:</b>
  <%= @profesor.apellido_materno %>
</p>

<p>
  <b>Email:</b>
  <%= @profesor.email %>
</p>


<%= link_to 'Edit', edit_profesor_path(@profesor) %> |
<%= link_to 'Back', profesors_path %>